prep-javascript-objects - Patricia Manalang
patriciamanalang/prep-0722-code-solutions pull request #11
Opened 2022-08-09 20:23 UTC by patriciamanalang

<img width="536" alt="Screen Shot 2022-08-09 at 1 16 04 PM" src="https://user-images.githubusercontent.com/109925604/183753449-c0cb3e82-a2bf-4a6b-ba01-e0741c2dd229.png">

2022-08-10 18:12 UTC, thebearingedge requested changes

2022-08-10 18:12 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +var fullName = firstName + lastName;
Hi Patricia, for this exercise you can get the first name and last name of the person using dot notation.

```js
var fullName = person.firstName + ' ' + person.lastName;
```

2022-08-10 23:56 UTC, patriciamanalang commented
<img width="1329" alt="Screen Shot 2022-08-10 at 4 54 40 PM" src="https://user-images.githubusercontent.com/109925604/184042625-f75740d7-bc86-4d6c-8439-6085ce0c85c7.png">

2022-08-11 00:14 UTC, thebearingedge approved these changes

2022-08-11 00:15 UTC, merged